apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  defaultTriggers: |
    - on-deployed
    - on-health-degraded
    - on-sync-failed
    - on-sync-running
    - on-sync-status-unknown
    - on-sync-succeeded
