apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  context: |
    argocdUrl: https://argocd.sakamo.dev
  service.slack: |
    token: $slack-token
    icon: ":face_with_rolling_eyes:"
  service.mattermost: |
    token: $mattermost-token
    icon: ":face_with_rolling_eyes:"
  service.github: |
    appID: 100686
    privateKey: $github-privateKey
    installationID: 14747717
  service.telegram: |
    token: $telegram-token
