apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  context: |
    argocdUrl: https://argocd.sakamo.dev
  service.slack: |
    token: $slack-token
    icon: ":face_with_rolling_eyes:"
  service.webhook.mattermost: |
    url: https://sakamo.cloud.mattermost.com
    headers:
    - name: Authorization
      value: Bearer $mattermost-token
  service.github: |
    appID: 100686
    privateKey: $github-privateKey
    installationID: 14747717
