namespace: argocd
resources:
- ../../base
- sealedsecret.yml
patchesStrategicMerge:
- configmap.yml
images:
- name: argoprojlabs/argocd-notifications
  newName: gcr.io/sakamo-dev/argocd-notifications@sha256
  newTag: d442dc50eef909623d05b366fe56358ecd5531a4e6388f8b72ff4e1f06ae3989
