apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    slack-token: AgCm3f4beN8UwvZsq6MjkddTOhSu/2QG0BzztBK6U9HooDpsNHd0MH2uGGF7L/hLL25MgYyR5xRpMBD1+s5KEXkBNqi5oNAoakZ4GD+mJ6BavMIP7sepXt0vE7mgm1gqDBaSPbLvQtJXB0rEwQSyQJTLg3+KLNoH9UF1T81KltpS/KuYM1JpmG2V3grbV7G1ZAtxNIDVITyN9VUo8Zux+/wPfkPgnk6hS4QQGgUdZKWHKJ0xn4gKbmaKjCfv76I9xzYDlYtO3J83TtuR1FcekHv8cfVz2yAr7TTCTnGJadhI8mzszjLgD6sdLt6Y+80rUZFAqjglIfyUEaezOYPpmlvXYK82m6bf1TpQ3l31hO1ivxeJ6g1SKqg0oeJNzuyDCvF/aDRQ5sAGPdjs0pAFh98V1bR+QMXLNt3gQ4QsOr8ziQgY+iqgeeld6wQAcrHzU3ONG1tskwfoeycUVsvCCyr0qtnyBD915FJK3mvIVg64Nv/7Q4pE7sHp3DARiwQuWtVcHImKmVqMviEAGGAXAD07k0cyQ2kYRjK+4HUYWwE2v7255kQdZSvqXVAKqW+G0GHXBvjz13jXCkzs4ReWASVHKr7WMrVw0niwE8+vOvdYvjhaKdEZbVn8jTmWmpkfqTL3MZDQQ5EHJZxcGgawJJ+KREyURiFIH9ju1tQ1CLdIMIk+4pP/6scTbzEdbTMUHejcaFOb3WtFYuWvhaOgH4w6Bz/kS8Mh7V1XtVf2nIwW5jCe0Elj2knIXIL+f8TeSA7AlCgDGF+5/g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: argocd-notifications-secret
      namespace: argocd
