resources:
- ../../base
patchesStrategicMerge:
- apps.yml
- argocd.yml
commonAnnotations:
  notifications.argoproj.io/subscribe.slack: deploy_notifications
  notifications.argoproj.io/subscribe.telegram: argocd_sakamo_dev
