apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.default: role:readonly
  policy.csv: |
    g, ryota-sakamoto, role:admin
    g, sakamo.ryota+github@gmail.com, role:admin
  scopes: |
    - username
    - email
    - groups
